# Generated by Django 4.1.7 on 2023-12-03 14:01

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Myfarms',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('province', models.CharField(blank=True, max_length=40, null=True)),
                ('district', models.CharField(blank=True, max_length=40, null=True)),
                ('status', models.CharField(blank=True, max_length=25, null=True)),
                ('area_ha', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('area_acre', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('class_field', models.CharField(blank=True, db_column='class', max_length=100, null=True)),
                ('maize', models.FloatField(blank=True, null=True)),
                ('fertilizer', models.FloatField(blank=True, null=True)),
                ('sorghum', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=0)),
            ],
            options={
                'db_table': 'myfarms',
                'managed': False,
            },
        ),
    ]
