# Generated by Django 4.1.7 on 2023-12-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agric', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='provinces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
