# Generated by Django 4.1.7 on 2023-12-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agric', '0002_provinces'),
    ]

    operations = [
        migrations.CreateModel(
            name='farm_allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(blank=True, max_length=1000, null=True)),
                ('maize', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('fertilizer', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('sorghum', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='date updated')),
            ],
            options={
                'ordering': ('date_created',),
            },
        ),
    ]
