# Generated by Django 4.1.7 on 2023-12-03 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agric', '0004_province_allocation_delete_farm_allocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='farms_allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maize', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('fertilizer', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('sorghum', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='date updated')),
                ('farms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agric.myfarms')),
            ],
            options={
                'ordering': ('date_created',),
            },
        ),
    ]
