# Generated by Django 4.1.7 on 2023-12-09 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agric', '0006_newfarms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farms_allocation',
            name='farms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agric.newfarms'),
        ),
    ]
